#%RAML 1.0 DataType
type: object
properties:
  id:
    type: integer
    required: false
  first_name:
    type: string
    required: true
  last_name:
    type: string
    required: false
  date_of_birth:
    type: string
    required: true
  gender:
    type: string
    required: false